<?php

/*
 * Panther Demo
 *
 * Jeff Channell 2019
 */

namespace JeffChannell\PantherDemo\Tests\Suite\Panther;

/**
 * Panther Example 3.
 */
class Example3Test extends Example2Test
{
    /**
     * Test clicking a button generated by JavaScript.
     */
    public function test_button()
    {
        $client = static::createPantherClient();
        $crawler = $client->request('GET', '/js.php');

        $this->waitForDemo($client);

        $this->assertStringContainsString('Before AJAX', $crawler->html());

        $crawler->selectButton('Send Request')->click();
        $client->waitFor('.done');

        $this->waitForDemo($client);

        $html = $crawler->html();
        $this->assertStringContainsString('Thanks for your submission, Naboo.', $html);
    }

    /**
     * Test runner.
     *
     * @param string $name
     * @param int    $number
     * @param string $message
     *
     * @dataProvider cases_form
     */
    public function test_form(string $name, int $number, string $message)
    {
        $client = static::createPantherClient();
        $crawler = $client->request('GET', '/js.php');

        $this->waitForDemo($client);

        $this->assertStringContainsString('Before AJAX', $crawler->html());

        $client->executeScript('window.sendPostData(\''.(http_build_query(['name' => $name, 'number' => $number])).'\');');
        $client->waitFor('.done');

        $this->waitForDemo($client);

        $html = $crawler->html();
        $this->assertStringContainsString($name, $html);
        $this->assertStringContainsString($message, $html);
    }
}
